### PR TITLE
rm: Add -x flag to avoid cross mount points. 	Add -x flag to rm(1) to allow use to specify not to cross mount 	points when removing files recursively.

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by natano** [comment]
The SYNOPSIS in the manpage needs update and the -x option needs to be show as extension to POSIX in the STANDARDS section.

**Comment by grimreaper** [comment]
updated

**Comment by natano** [comment]
Thank you for the pull-request! I have committed your diff to master (see 8d31257148623d02c6adcd278c940e38414010cf).

**Comment by grimreaper** [comment]
Thanks for both!

**Pull request closed without merging**
